import { createHash } from 'node:crypto';
import { readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { defineConfig, type Plugin } from 'vite';

/** Every file under public/, as site-relative paths. */
function publicFiles(dir = 'public'): string[] {
  const out: string[] = [];
  const walk = (d: string) => {
    for (const f of readdirSync(d)) {
      const p = join(d, f);
      if (statSync(p).isDirectory()) walk(p);
      else out.push(relative('public', p).split('\\').join('/'));
    }
  };
  walk(dir);
  return out;
}

/**
 * Writes sw.js: precaches the exact files of this build so Zeer works offline after the first
 * visit (the people it's for often have patchy data). Cache name = hash of the file list.
 */
function serviceWorker(): Plugin {
  return {
    name: 'zeer-service-worker',
    apply: 'build',
    generateBundle(_opts, bundle) {
      const files = ['./', 'index.html', ...Object.keys(bundle), ...publicFiles()].filter((f) => f !== 'sw.js' && !f.endsWith('.map'));
      const version = createHash('sha256').update(files.join('\n')).digest('hex').slice(0, 12);
      const source = `// Generated by vite.config.ts at build time. Do not edit.
const CACHE = 'zeer-${version}';
const FILES = ${JSON.stringify(files)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).catch(() => caches.match('index.html')));
    return;
  }
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source });
    },
  };
}

// Relative base so the site keeps working if the repo (and so the Pages path) is renamed.
export default defineConfig({
  base: './',
  plugins: [serviceWorker()],
  build: {
    target: 'es2020',
    sourcemap: false,
    assetsInlineLimit: 2048,
  },
  test: {
    include: ['tests/**/*.test.ts'],
    environment: 'node',
  },
} as never);
